### ISSUE TITLE
SMUI/Solr path mismatch on fresh checkout

### ISSUE THREAD

**Issue by renekrie** [querqy/chorus#11] opened 2020-08-08 16:33 UTC
When I fire up Docker on a fresh git clone and follow the README, SMUI reports a successful push to Solr but the rules.txt file in the conf folder of the Solr core is not modified. It turns out that SMUI does not push to the conf folder but to a different path.

We should fix this so that SMUI Solr work together out-of-the-box under Chorus.

**Comment by epugh** [comment] 2020-08-08 19:58
I'm going to look at this, because the way we had it set up was that in Solr, it was to the `./conf/querqy/rules.txt` folder, and that was because of some docker magic to share that same folder between Solr and SMUI....

**Comment by epugh** [comment] 2020-08-08 20:20
Okay, I just gave it a freshcheckout, and ran the `quickstart.sh` script.    Went into SMUI, and added a rule, and published to Solr, then checked Solr via:

```
http://localhost:8983/solr/ecommerce/admin/file?wt=json&_=1596917848640&file=querqy%2Frules.txt&contentType=text%2Fplain%3Bcharset%3Dutf-8
```
and confirmed it published.    Can you confirm that there is NO `/conf/rules.txt`, but that there is a `/conf/querqy/rules.txt`.

**Comment by renekrie** [comment] 2020-08-09 20:59
I didn't use the `quickstart.sh` script but ran the steps from README manually. I'll re-try.

**Comment by epugh** [comment] 2020-08-09 21:01
The two should be the same steps, so this is a good test!!!

**Comment by renekrie** [comment] 2020-08-09 21:54
After pruning everything on Docker (`docker system prune --volumes`) and after a fresh run-through of the steps from  the README, pushing from SMUI works as expected (i.e. rules are pushed and activated).  But it looks like the SMUI version got downgraded. I'm now seeing 3.6.1 (=works), whereas I'm 'pretty sure' I saw the new spelling feature in SMUI (at least  SMUI 3.7.x - https://docs.querqy.org/smui/index.html#major-changes-in-v3-7 ) before (didn't work). How could this happen? Also pinging @pbartusch

**Comment by epugh** [comment] 2020-08-10 11:59
The SMUI docker build in Chorus is still tied to 3.6.1: https://github.com/querqy/chorus/blob/master/smui/Dockerfile#L1   We should fix this via a branch probably.

**Comment by epugh** [comment] 2020-08-17 16:44
Closing as Not a Bug.

**Closed by epugh** 2020-08-17 16:44 UTC
Labels: bug
